const items = [
    {
        _id: 0,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 1,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 2,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 3,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 4,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 5,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 6,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 7,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 8,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
    {
        _id: 9,
        image: 'default.jpeg',
        name: '12345678 Вешалка настенная 63x118x20 см, цвет дуб сонома',
        sku: {
            active: 136,
            withStocks: 6,
            withoutStocks: 3,
        },
        type: 'компоненты',
        id: '3452 - 4436',
        checked: false,
    },
];

export default items;